# APPLICATION
spring.application.name=market

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# FLYWAY
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT TOKEN EXPIRATION
app.security.jwt.access-token-expiration=86400000
app.security.jwt.refresh-token-expiration=604800000

# DISPOSABLE EMAIL DOMAINS
app.security.disposable-email=10minutemail,20minutemail,33mail,5ymail,anonbox,guerrillamail,mailinator,maildrop,mailnesia,moakt,my10minutemail,throwawaymail,trashmail,temp-mail,tempmail,truemail,yopmail

# EMAIL CONFIGURATION
app.email.password-reset-token-expiration-minutes=10

# PASSWORD POLICY (90 days)
security.password.expiration-minutes=129600

# LOGIN ATTEMPT PROTECTION
security.login-attempt.max-attempts=5
security.login-attempt.lock-duration-minutes=15

spring.profiles.active=local

# LOGGING
# logging.level.org.flywaydb=DEBUG
# logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG