# DATABASE
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT KEYS
jwt.private-key-path=private key path
jwt.public-key-path=public keys path

# EMAIL CONFIGURATION
app.email.frontend-url=${FRONTEND_URL}

# BREVO CONFIGURATION
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL}
brevo.sender.name=${BREVO_SENDER_NAME}
brevo.url=${BREVO_URL}