# DATABASE
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT KEYS
jwt.private-key-path=private key path
jwt.public-key-path=public keys path

# EMAIL CONFIGURATION
app.email.frontend-url=${FRONTEND_URL}

# BREVO CONFIGURATION
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL}
brevo.sender.name=${BREVO_SENDER_NAME}
brevo.url=${BREVO_URL}

# Administrator configuration
app.initial-admin.email=${INITIAL_ADMIN_EMAIL}
app.initial-admin.password=${INITIAL_ADMIN_PASSWORD}
app.initial-admin.phone=${INITIAL_ADMIN_PHONE}

#google OAuth configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

app.frontend.oauth2-success-url=${FRONTEND_OAUTH2_SUCCESS_URL}
app.security.oauth2.login-code-expiration-seconds=60